### ISSUE TITLE
Someone, please get all class infomation  from the syllabus on the web

### ISSUE THREAD

**Issue by v010maaa** [sunada-t/PBL_SE_team#14]
Someone, please get all class infomation  from the syllabus on the web. And put it in csv.
Example
**classname    classID    teacher    etc...**
Artificial intelligence   3032    Sunada      ....
Machine learning    2231      aaaa     ....

**Comment by v010maaa** [comment]
This may not be necessary. Because we can get classID.  Also weekly schedules are created from monthly schedules.
Common 1000 --- 
Foundation 2000 ---
Specialty 3000 ----

**Comment by ifrazrehman** [comment]
[class_info_final.xlsx](https://github.com/sunada-t/PBL_SE_team/files/4121010/class_info_final.xlsx)
this file is in .xls entension. you can convert it to .csv for further use. database for class information as per said instruction.

**Comment by sunada-t** [comment]
Ifraz-san. Thank you. I confirmed.
"class_info_final.xlsx" was reflected.
I close this issue.
