### ISSUE TITLE
Remaining units calculation page: scraping

### ISSUE THREAD

**Issue by sunada-t** [sunada-t/PBL_SE_team#18]
Please do scraping
https://subjregist.naist.jp/registrations/preview_list

**Comment by v010maaa** [comment]
![スクリーンショット 2020-01-21 19 25 50](https://user-images.githubusercontent.com/49779936/72797129-e8a91980-3c83-11ea-8925-816b4832a68b.png)

**Comment by v010maaa** [comment]
Data was obtained like this.  It is difficult to divide each item(class, classID, teacher). 
However they can be separated because they are arranged regularly.
