### ISSUE TITLE
Robustness Diagram

### ISSUE THREAD

**Issue by sunada-t** [sunada-t/PBL_SE_team#3]
![Untitled Diagram-Robustness Diagram](https://user-images.githubusercontent.com/49709970/71400454-2e18fd80-266a-11ea-909a-2f0887cfef9e.png)

**Comment by ifrazrehman** [comment]
![Robustness_update](https://user-images.githubusercontent.com/43130832/73718610-611dd900-4760-11ea-98d3-8ae6d3de9ac2.png)
I updated the robustness diagram as per application design
