### ISSUE TITLE
Use Case

### ISSUE THREAD

**Issue by sunada-t** [sunada-t/PBL_SE_team#4]

**Comment by sunada-t** [comment]
![Untitled Diagram-Use Case (1)](https://user-images.githubusercontent.com/49709970/71400828-45a4b600-266b-11ea-9a45-e77613ea8264.png)

**Comment by ifrazrehman** [comment]
![Use_case_update](https://user-images.githubusercontent.com/43130832/73719715-9841b980-4763-11ea-88b8-bf26e7e58ac7.png)
I update the use case as per application design.
