### ISSUE TITLE
Robustness diagrams : Automatic timetable  generation page

### ISSUE THREAD

**Issue by sunada-t** [sunada-t/PBL_SE_team#6]

**Comment by sunada-t** [comment]
I do this

**Comment by sunada-t** [comment]
NAISTホームページの月別授業日程からスクライピングをする
それを基に時間割を作成

**Comment by v010maaa** [comment]
undo

**Comment by sunada-t** [comment]
[Robustness _ Automatic timetable generation page.pdf](https://github.com/sunada-t/PBL_SE_team/files/4029306/Robustness._.Automatic.timetable.generation.page.pdf)

**Comment by sunada-t** [comment]
![detail design_Automatic timetable generation page](https://user-images.githubusercontent.com/49709970/72313866-216b5080-36d0-11ea-939c-aa879a1b1ff1.png)
